name: CI pipeline voor mn kleine Java/SpringBoot front- en backend projece

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout deze code
      uses: actions/checkout@v2

    - name: Set de java op tenminste JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Bouw het met Maven
      run: mvn clean package

    - name: Run tests...al is het void!
      run: mvn test
