name: CI pipeline voor mn kleine Java/SpringBoot front- en backend project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build-step.outcome }}
    steps:
    - name: Checkout deze code
      uses: actions/checkout@v2

    - name: Zet Java op JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'  # adopt wordt niet meer aangeraden

    - name: Bouw het project
      id: build-step
      run: mvn clean package

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout deze code
      uses: actions/checkout@v2

    - name: Zet Java op JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Voer tests uit
      run: mvn test
